(setq-local indent-tabs-mode nil)
(setq-local tab-width 2)
(setq-local tab-stop-list (number-sequence 2 200 2))
(setq-local evil-shift-width 2)

(auto-complete-mode 1)
(rainbow-mode 1)
(rainbow-delimiters-mode 1)
(smartparens-mode 1)
(structured-haskell-mode 1)
(turn-on-eldoc-mode)
(turn-on-haskell-doc)
(turn-off-haskell-simple-indent)
