(auto-fill-mode 1)
(flyspell-mode 1)
(LaTeX-math-mode 1)
(setq-local fill-column 80)
(setq-local indent-tabs-mode nil)
(setq-local tab-width 2)
(setq-local tab-stop-list (number-sequence 2 200 2))
(setq-local evil-shift-width 2)
