(autopair-mode 1)
(highlight-indentation-current-column-mode 1)
(rainbow-mode 1)
(rainbow-delimiters-mode 1)
(rainbow-identifiers-mode 1)
(smartparens-mode 1)
(yas/minor-mode 1)

(setq-local fill-column 80)
(setq-local evil-shift-width 2)
(setq-local tab-width 2)
(setq-local tab-stop-list (number-sequence 2 200 2))
(setq-local indent-tabs-mode nil)

(setq-local comment-start "// ")
(setq-local comment-end "")
