(setq-local fill-column 72)
(setq-local indent-tabs-mode nil)
(setq-local tab-stop-list (number-sequence 2 72 2))
(setq-local evil-shift-width 2)
(setq-local tab-width 2)

(smartparens-mode 1)
(rainbow-mode 1)
(rainbow-delimiters-mode 1)
(highlight-indentation-current-column-mode 1)
