;; Functions - my functions in Emacs Lisp. Most of these are just
;; shortcuts to other functions.

(defalias 'bb 'ido-switch-buffer)
(defalias 'bbo 'ido-switch-buffer-other-window)
(defalias 'bft 'direx:jump-to-directory-other-window)
(defalias 'bl 'ibuffer)
(defalias 'bury 'bury-buffer)
(defalias 'dr 'ido-dired)
(defalias 'dro 'dired-other-window)
(defalias 'eb 'eval-buffer)
(defalias 'ee 'eval-expression)
(defalias 'er 'eval-region)
(defalias 'ff 'ido-find-file)
(defalias 'ffo 'ido-find-file-other-window)
(defalias 'k 'kill-this-buffer)
(defalias 'kb 'kill-this-buffer)
(defalias 'kbn 'ido-kill-buffer)
(defalias 'kow 'delete-other-windows)
(defalias 'kw 'delete-window)
(defalias 'ow 'other-window)
(defalias 'ri 'yari)
(defalias 'sa 'mark-whole-buffer)
(defalias 'sp 'split-window-below)
(defalias 'vsp 'split-window-right)
(defalias 'xx 'execute-extended-command)
