#! /bin/sh

xrandr --output DVI-D-2 --right-of DVI-D-1
setxkbmap us -variant colemak

bspc monitor DVI-D-1 -d I III V VII IX
bspc monitor DVI-D-2 -d II IV VI VIII X

bspc config border_width        3
bspc config window_gap          15
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

