#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        10
bspc config window_gap          25
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# bspc rule -a Gimp desktop=^8 follow=on floating=on
# bspc rule -a Chromium desktop=^2
# bspc rule -a mplayer2 floating=on
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

setxkbmap us,ru -variant colemak, -option \
          terminate:ctrl_alt_bksp,grp:rctrl_toggle,compose:ralt,ctrl:nocaps &
nitrogen --restore &

