;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-backward-word-begin
        evil-change
        evil-delete-char
        evil-ex
        evil-find-char-to
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-invert-char
        evil-normal-state
        evil-previous-line
        markdown-exdent-or-delete
        ))

(setq mc/cmds-to-run-once
      '(
        ))
