;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-insert-opening
		autopair-insert-or-skip-quote
		autopair-skip-close-maybe
		comment-dwim
		evil-backward-char
		evil-change
		evil-delete
		evil-ex
		evil-exit-visual-state
		evil-force-normal-state
		evil-forward-char
		evil-insert
		evil-normal-state
		markdown-dedent-or-delete
		markdown-exdent-or-delete
		python-indent-electric-colon
		python-indent-shift-left
		python-indent-shift-right
		toggle-comment
		vi-open-line-above
		))

(setq mc/cmds-to-run-once
      '(
		backward-delete-char
		compile
		evil-visual-block
		find-file
		help-follow-mouse
		))
