;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		10-lines-up
		TeX-insert-backslash
		autopair-insert-opening
		autopair-insert-or-skip-quote
		autopair-skip-close-maybe
		comment-dwim
		downcase-region
		evil-backward-char
		evil-change
		evil-delete
		evil-ex
		evil-exit-visual-state
		evil-force-normal-state
		evil-forward-char
		evil-insert
		evil-normal-state
		fill-paragraph
		insert-backtick
		keyboard-escape-quit
		markdown-dedent-or-delete
		markdown-exdent-or-delete
		mouse-yank-primary
		python-indent-dedent-line-backspace
		python-indent-electric-colon
		python-indent-shift-left
		python-indent-shift-right
		tab-to-tab-stop
		tex-terminate-paragraph
		toggle-comment
		toggle-fullscreen
		upcase-region
		vi-open-line-above
		wdired-finish-edit
		))

(setq mc/cmds-to-run-once
      '(
		backward-delete-char
		compile
		evil-visual-block
		find-file
		help-follow-mouse
		magit-status
		))
